Update action.yaml

diff --git a/images/chr-source/action.yaml b/images/chr-source/action.yaml
--- a/images/chr-source/action.yaml
+++ b/images/chr-source/action.yaml
@@ -13,17 +13,20 @@ runs:
       shell: bash
       run: |
         VERSION="${{ inputs.version }}"
-        IS_PRESENT=$(docker manifest inspect uazo/chromium:$VERSION > /dev/null ; echo $?)
+        IS_PRESENT=$(docker inspect --type=image uazo/chromium:$VERSION > /dev/null ; echo $?)
         if [ $IS_PRESENT -ne "0" ]; then
-          echo "Image not found"
+          IS_PRESENT=$(docker manifest inspect uazo/chromium:$VERSION > /dev/null ; echo $?)
+          if [ $IS_PRESENT -ne "0" ]; then
+            echo "Image not found"
           
-          mkdir chr-source
-          pushd chr-sourced/
+            mkdir chr-source
+            pushd chr-sourced/
           
-          git clone https://github.com/uazo/bromite-buildtools
-          cd bromite-buildtools/images/chr-source/
-          docker build -t uazo/chromium:$VERSION --progress plain --build-arg VERSION=$VERSION .
+            git clone https://github.com/uazo/bromite-buildtools
+            cd bromite-buildtools/images/chr-source/
+            docker build -t uazo/chromium:$VERSION --progress plain --build-arg VERSION=$VERSION .
 
-          popd
-          rm -rf chr-source
+            popd
+            rm -rf chr-source
+          fi
         fi
